package:
    name: yamanifest
    version: {{ GIT_DESCRIBE_TAG }}

build:
    number: {{ GIT_DESCRIBE_NUMBER }}
    string: {{ GIT_BUILD_STR }}

source:
    git_url: ../

build:
    script: python setup.py install

requirements:
    build:
        - python
        - pbr
    run:
        - python
        - six
        - pyyaml
        - nchash

test:
    source_files:
        - setup.cfg
        - conftest.py
        - test
    requires:
        - pytest
    commands:
        - py.test -s

about:
    home: https://github.com/aidanheerdegen/yamanifest
    license: Apache 2.0
    license_file: LICENSE-2.0.txt
    summary: General YAML manifest format
